### ISSUE TITLE
[Crash]attempt to index global 'Keepers' (a nil value)

### ISSUE THREAD

**Issue by PJzuza** [segabl/pd2-keepers-joker-names#5]
[My crash.txt](https://pastebin.com/gdBqJTpa) 
Reproducible crash
Lately. I've tested the vanilla game by taking Full speed swarm mods and Iter out but I forgot to take the Keeper mod out as well. Without Iter. The mod Keeper won't be activated since it has the dependency mods in mod.txt but Keeper Joker Names is still activated and it will crash your game if you continue using it. ~~My suggestion is adding "KPR" as a dependency mod should do the trick. Let me know if you want me to update your mod.txt~~ Okay... forget what I have said... It's something else I think but I have no idea what caused it sadly.
Edited: BLT's fault it seems... Thanks to TdlQ's testing. I'm appreciated your kindness a lot. Still. I'll keep opening this for now (unless you want to close it @segabl ) and here is what he said.
> TdlQ:  BLT doesn't check dependencies correctly. Iter absents => Keepers is not loaded but since Keepers is presented => it loads Keeper Joker Names

**Comment by segabl** [comment]
I think a disabled Keepers should trigger a message from BLT that it is needed. Seems like a BLT issue indeed.

**Comment by PJzuza** [comment]
Fixed thanks to TdlQ [PR on BLT](https://github.com/JamesWilko/Payday-2-BLT-Lua/pull/81) so I'll close this for now. If other people still experienced the same issue then I'll refer this thread to them again. Sorry for the trouble.
