### ISSUE TITLE
The mod shows an update in-game even when manually downloading the last version

### ISSUE THREAD

**Issue by Joldror** [segabl/pd2-keepers-joker-names#6]
It shows an update wich of course fails when attempted. My best guess is that the 'updates' json has an incorrect hash. I don't think is an error on my part but could be. I'd apreciate some clarification. Thanks.

**Comment by segabl** [comment]
make sure you deleted the old mod folder, it's named differently than the new one so BLT might get confused

**Comment by Joldror** [comment]
Multiple times. Removed old version, removed new version and redownloaded even changed new version folder name. No change. I just tried to empty the downloads folder, just in case, but still nothing.

**Comment by segabl** [comment]
Hmm that is certainly weird. I just checked and indeed it fails to update. This seems to be one of BLTs long standing issues. I'll see if pushing a new version will fix it.
