### ISSUE TITLE
[Crash] "Attempted to index value 'names' (a null value)

### ISSUE THREAD

**Issue by Scouter953** [segabl/pd2-keepers-joker-names#8]
Every time I take a Joker, I get a crash with this reasoning. I've updated everything, including going so far as to uninstall this mod completely and install a fresh version. Same result every time.

**Comment by segabl** [comment]
Can you post the full crash log?

**Comment by Scouter953** [comment]
Sun Jul 26 22:54:25 2020


Application has crashed: C++ exception
mods/Keepers Joker Names/joker_names.lua:29: attempt to index field 'names' (a nil value)



SCRIPT STACK

set_joker_name() @mods/Keepers Joker Names/joker_names.lua:91
interact() @mods/Keepers Joker Names/joker_names.lua:137
end_action_interact() lib/managers/objectinteractionmanager.lua:86
_end_action_interact() lib/units/beings/player/states/playerstandard.lua:2420
_update_interaction_timers() lib/units/beings/player/states/playerstandard.lua:2464
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:871
fs_original_playerstandard_update() lib/units/beings/player/states/playerstandard.lua:435
update() @mods/Full Speed Swarm/lua/playerstandard.lua:6
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:265


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.95.896
	CPU : AMD Ryzen 7 1700 Eight-Core Processor (8 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 / nvldumd.dll[27.21.14.5167]
	Language : english
	Memory :     16316MB 716KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VB-Audio Software (CABLE-A Input (VB-Audio Cable A))

**Comment by segabl** [comment]
Looks like you still have an old version of the mod around. Make sure you delete the ``Keepers Joker Names`` folder and that you only have the one named ``pd2-keepers-joker-names-master``

**Comment by Scouter953** [comment]
As I said, I've done that before. I tried it again just to check and the same problem happens again.

**Comment by segabl** [comment]
This part: ``mods/Keepers Joker Names/joker_names.lua:29`` tells me you still have an old version. Delete that folder.

**Comment by Scouter953** [comment]
I told you - I did. I renamed the folder because it looks better in the mod list. What part of "I tried it again just to check" was vague?

**Comment by Scouter953** [comment]
Fri Jul 31 13:29:06 2020


Application has crashed: C++ exception
mods/pd2-keepers-joker-names-master/joker_names.lua:33: attempt to index field 'names' (a nil value)



SCRIPT STACK

set_joker_name() @mods/pd2-keepers-joker-names-master/joker_names.lua:95
interact() @mods/pd2-keepers-joker-names-master/joker_names.lua:125
end_action_interact() lib/managers/objectinteractionmanager.lua:86
_end_action_interact() lib/units/beings/player/states/playerstandard.lua:2420
_update_interaction_timers() lib/units/beings/player/states/playerstandard.lua:2464
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:871
fs_original_playerstandard_update() lib/units/beings/player/states/playerstandard.lua:435
update() @mods/Full Speed Swarm/lua/playerstandard.lua:6
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:265


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.95.896
	CPU : AMD Ryzen 7 1700 Eight-Core Processor (8 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 / nvldumd.dll[27.21.14.5167]
	Language : english
	Memory :     16316MB 716KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VB-Audio Software (CABLE-A Input (VB-Audio Cable A))

**Comment by segabl** [comment]
ok, first of all, you shouldn't rename the folder as it will break automatic updates, second of all, the original crash happened in a line that doesn't make sense for the current state of the mod, that's why I assumed you had an old version. the one you posted now makes sense line number wise. I'm still not sure what's happening there exactly as it complains about not having the names table, which is pretty much impossible. have you tried deleting the settings file of the mod from mods/saves?

**Comment by Scouter953** [comment]
Really? The updates seemed fine to me. Huh. And I'll try that next time I have a chance and will update.

**Comment by segabl** [comment]
The updates will download fine but it will create said duplicate folders, since BLT can only remove the old mod folder if it's the same name as the new one.

**Comment by Scouter953** [comment]
Holy fuck, that actually worked. Thanks for your help, man! That was so aggravating as this was the only mod still having problems. All seems good now.
